name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: develop
    environment: develop
    steps:
      - uses: actions/checkout@v6          
      - name: Copiar a /opt/services/forgeMin
        run: |
          sudo mkdir -p /opt/services/forgeMin
          sudo rm -rf /opt/services/forgeMin/*
          sudo cp -r . /opt/services/forgeMin
          sudo cp /opt/services/variables/.env.forgeMin /opt/services/forgeMin/backend/.env

      - name: Docker Compose 
        run: |
          cd /opt/services/forgeMin
          sudo docker builder prune -f
          sudo docker compose down
          sudo docker compose build --no-cache
          sudo docker compose up -d

  frontend:
    runs-on: develop
    environment: develop
    steps:
      - uses: actions/checkout@v6
      - name: Instalar dependencias
        run: npm ci --include-workspace-root=false
      - name: Copiar variables de entorno
        run: |
          sudo cp /opt/services/variables/.env.forgemind.frontend ./frontend/.env.local

      - name: Build frontend
        run: npm run build -w frontend

      - name: Serve frontend
        run: |
          sudo mkdir -p /usr/share/nginx/forgemind/
          sudo rm -rf /usr/share/nginx/forgemind/*
          sudo cp -r frontend/out/* /usr/share/nginx/forgemind/
          sudo systemctl reload nginx
